name: Build RFQ for SKiDL

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: python src/main.py